### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by yonahforst** [bakerface/easy-source#1]
Hi! I found this repo after finding your `dynamodb-event-store` 😀

I've been looking for days for something like this; I want to try event sourcing in my serverless app (hosted on aws). 

I'm writing to see if this library is just a proof of concept, or something more. I had some issues integrating it with `dynamodb-event-store` and `dynamodb-snapshot-store` (just some naming convention stuff that I was able to work around). But I wanted to check with you first before submitting PRs, and see what your plans are with this.

It's really, really nice work! I would love to use it in my app.

**Comment by bakerface** [comment]
I am reworking the interface to a v2. It should be pushed in the next few days. Glad you are interested! Feel free to send pull requests after I push.

**Comment by bakerface** [comment]
I just pushed the v2 release. It comes with support for snapshots, projections spanning multiple event stores, and a few other cool features. Take a look at the example application if you are interested. I spent a while making sure that everything works even on platforms as old as node 0.10.x and threw out all of the external dependencies (except for bluebird as I wanted Promise support for older node versions). Let me know if you find it useful.

In regards to `dynamodb-event-store`, the naming conventions do not align as you mentioned. I hope to get some time in the next few days to rework that package as well so that it is compatible with the event store API for this framework.

**Comment by yonahforst** [comment]
@bakerface - thanks so much for the replies. I'm poking around the example now, looks super interesting. 

I'd love to learn more about the way you structured the domain. Do you have any links or maybe even just some google search terms to put me on the right path?
